name: CI

on: [push]

jobs:
  mlx-test:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get Hugging Face cache directory
        id: hf-cache-dir
        run: echo "dir=$(pip cache dir)/huggingface/hub" >> $GITHUB_OUTPUT
      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ${{ steps.hf-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-hf-cache-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-hf-cache-
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Sync dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest -s tests
